- repo: git@github.com:pre-commit/pre-commit-hooks
  sha: ff65d01841ad012d0a9aa1dc451fc4539d8b7baf
  hooks:
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: detect-aws-credentials
- repo: git@github.com:hootsuite/pre-commit-php.git
  sha: 1.1.0
  hooks:
  - id: php-lint-all
  - id: php-unit
  - id: php-cs
    files: \.(php)$
    args: ['-p', '--standard=vendor/helpscout/php-standards/HelpScout', '--warning-severity=0']
- repo: git://github.com/Lucas-C/pre-commit-hooks
  sha: b600798f8dacfcc29862e3d58367b89d3090c6a7
  hooks:
  - id: forbid-crlf
  - id: forbid-tabs
- repo: local
  hooks:
  - id: check-bash-syntax
    name: Check Shell scripts syntax corectness
    language: system
    entry: bash -n
    files: \.sh$
